# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(272327)
$foreground = rgb(F4ECBF)
$color0 = rgb(4D484D)
$color1 = rgb(5E2331)
$color2 = rgb(4B4553)
$color3 = rgb(A03A3A)
$color4 = rgb(686B75)
$color5 = rgb(686A75)
$color6 = rgb(A79636)
$color7 = rgb(E6DB9B)
$color8 = rgb(A1996C)
$color9 = rgb(7E2E42)
$color10 = rgb(645C6E)
$color11 = rgb(D64D4E)
$color12 = rgb(8B8E9C)
$color13 = rgb(8B8E9C)
$color14 = rgb(DFC848)
$color15 = rgb(E6DB9B)
