# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2E2D2D)
$foreground = rgb(FAF1E4)
$color0 = rgb(535252)
$color1 = rgb(2B211F)
$color2 = rgb(5E1B16)
$color3 = rgb(611A15)
$color4 = rgb(611A15)
$color5 = rgb(B8231D)
$color6 = rgb(B4A185)
$color7 = rgb(EFE2D0)
$color8 = rgb(A79E91)
$color9 = rgb(392C2A)
$color10 = rgb(7D241D)
$color11 = rgb(82231C)
$color12 = rgb(82231C)
$color13 = rgb(F62F27)
$color14 = rgb(F0D6B1)
$color15 = rgb(EFE2D0)
