# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(302F2F)
$foreground = rgb(EEE5DA)
$color0 = rgb(545454)
$color1 = rgb(252322)
$color2 = rgb(2A2525)
$color3 = rgb(5B323A)
$color4 = rgb(743844)
$color5 = rgb(62605E)
$color6 = rgb(9A8970)
$color7 = rgb(DED2C2)
$color8 = rgb(9B9387)
$color9 = rgb(312F2E)
$color10 = rgb(383131)
$color11 = rgb(7A424D)
$color12 = rgb(9B4B5B)
$color13 = rgb(83807D)
$color14 = rgb(CDB695)
$color15 = rgb(DED2C2)
