# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6FBFD
background         #1B1D21
cursor             #8DAAB8

active_tab_foreground     #1B1D21
active_tab_background     #F6FBFD
inactive_tab_foreground   #F6FBFD
inactive_tab_background   #1B1D21

active_border_color   #F6FBFD
inactive_border_color #1B1D21
bell_border_color     #4A0D59

color0      #414449
color1		#4A0D59
color2		#1B4357
color3		#21526A
color4		#337C9D
color5		#3580A2
color6		#ABB7BA
color7		#E9F1F3
color8		#A3A9AA
color9		#621176
color10		#245974
color11		#2D6D8D
color12		#44A5D2
color13		#46AAD8
color14		#E4F4F8
color15		#E9F1F3
