# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F2BBB2
background         #1F1D1D
cursor             #A77169

active_tab_foreground     #1F1D1D
active_tab_background     #F2BBB2
inactive_tab_foreground   #F2BBB2
inactive_tab_background   #1F1D1D

active_border_color   #F2BBB2
inactive_border_color #1F1D1D
bell_border_color     #1B1615

color0      #454443
color1		#1B1615
color2		#441D18
color3		#61241B
color4		#812A1C
color5		#A32D1B
color6		#A42D1B
color7		#E49589
color8		#A06860
color9		#251D1C
color10		#5B2720
color11		#813024
color12		#AB3826
color13		#DA3C24
color14		#DA3C24
color15		#E49589
