# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDEFDB
background         #15171C
cursor             #808385

active_tab_foreground     #15171C
active_tab_background     #FDEFDB
inactive_tab_foreground   #FDEFDB
inactive_tab_background   #15171C

active_border_color   #FDEFDB
inactive_border_color #15171C
bell_border_color     #031124

color0      #3C3E44
color1		#031124
color2		#031124
color3		#1A4D62
color4		#4A828A
color5		#A27771
color6		#BA9C71
color7		#F3DFC3
color8		#AA9C88
color9		#041730
color10		#041730
color11		#226682
color12		#63ADB8
color13		#D89E97
color14		#F8D097
color15		#F3DFC3
